---
ci:
  exclude:
    - pip-tools
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
          - prettier-plugin-sort-json
  - repo: https://github.com/PyCQA/doc8.git
    rev: v1.1.0
    hooks:
      - id: doc8
  - repo: https://github.com/python/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.2.2
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]
        args: []
        require_serial: false
        additional_dependencies: []
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.12.1
    hooks:
      - id: pip-compile
        entry: pip-compile --resolver=backtracking -q --no-annotate --output-file=requirements.txt pyproject.toml --extra test --strip-extras
        language: python
        files: ^(requirements\.txt|pyproject\.toml)$
        alias: deps
        language_version: "3.9" # minimal we support officially
        additional_dependencies:
          - pip>=22.3.1
      - id: pip-compile
        entry: pip-compile --resolver=backtracking -q --no-annotate --output-file=requirements.txt pyproject.toml --extra test --strip-extras --upgrade
        language: python
        files: ^(requirements\.txt|pyproject\.toml)$
        alias: up
        stages: [manual]
        language_version: "3.9" # minimal we support officially
        additional_dependencies:
          - pip>=22.3.1
